%YAML 1.1 # Terras configuration file
---
title: Terras Engine Test

# Graphics configuration
width: 1440
height: 720
fullscreen: false
fov: 45
sensitivity: 0.4

# Game resource files
nodefile: "data/node.yaml"
current_node: "node1"


